<a href="https://colab.research.google.com/github/shineloveyc/Deep-Learning_Exercise/blob/main/PyTorch_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
double_points = torch.ones(10, 2, dtype=torch.double)

In [ ]:
double_points.dtype

torch.float64

In [ ]:
short_points = torch.ones(10, 2, dtype=torch.short)

In [ ]:
short_points.dtype

torch.int16

In [ ]:
mid_points = torch.tensor([[1,2], [3,4]], dtype=torch.short)

In [ ]:
points = torch.rand(10,2)
points

tensor([[0.0419, 0.8695],
        [0.4303, 0.7395],
        [0.7016, 0.1339],
        [0.0357, 0.4711],
        [0.9851, 0.3864],
        [0.0572, 0.3422],
        [0.5875, 0.5593],
        [0.2886, 0.5958],
        [0.4196, 0.0767],
        [0.4907, 0.4738]])

In [ ]:
points.dtype

torch.float32

In [ ]:
#cast a tensor of one type to another type
short_points = points.type(torch.short)
short_points

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int16)

In [ ]:
some_list = list(range(6))
some_list[:]

[0, 1, 2, 3, 4, 5]

In [ ]:
#step at 2, from 0-3
some_list[1:4:2]

[1, 3]

In [ ]:
#covert tensor to numpy array
points = torch.ones(10, 2, dtype = torch.int32)

In [ ]:
num_points = points.numpy()
num_points.dtype

dtype('int32')

In [ ]:
num_points

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [ ]:
#covert numpy array to torch tensor
torch_points = torch.from_numpy(num_points)
torch_points

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)

In [ ]:
#save data
#torch.save(torch_points, 'file_path')

In [ ]:
#load data
#points = torch.load('file_path)

In [ ]:
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]],
device='cuda')

In [ ]:
#cope a tensor created on CPU to GPU
points_gpu = points.to(device = 'cuda')

In [ ]:
points_cpu = points.to(device = 'cpu')
points_cpu = points.cpu() #short methor

In [ ]:
#create a tensor a 
a = torch.tensor(list(range(9)))
a
print(a.size())
a.storage()

torch.Size([9])


 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]

In [ ]:
a.stride()

(1,)

In [ ]:
b = a.view(3,3)

In [ ]:
b[1,1]

tensor(4)

In [ ]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
c = b[1:, 1:]

In [ ]:
c.size()

torch.Size([2, 2])

In [ ]:
c.storage_offset()

4

In [ ]:
c.stride()

(3, 1)

In [ ]:
torch.max(a)

tensor(8)

In [ ]:
some_tensor = torch.ones(3, 4, 5)
some_tensor

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [ ]:
#specify 1st an 2nd dimension to be transfered
some_tensor_t = some_tensor.transpose(0, 2)

In [ ]:
some_tensor_t

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
some_tensor_t.shape

torch.Size([5, 4, 3])

In [ ]:
#add dimension to current tenosr
a = torch.ones(2,2)
a.unsqueeze(0)

tensor([[[1., 1.],
         [1., 1.]]])

In [ ]:
#remove a dimension just created
a.squeeze(0)
a

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
#create a random of shape 5*3 in the interval of [3, 7)

tensor_two = 3 + torch.rand(5,3) *(7-3)

tensor_two

tensor([[3.9926, 6.5973, 4.4461],
        [3.7275, 4.4088, 5.7046],
        [5.0430, 6.7282, 5.1941],
        [5.2092, 5.8302, 3.5231],
        [6.3243, 3.8731, 6.3444]])

In [ ]:
#creat a tensor with values from normal distribution
norm_tensor = torch.rand(3,4)

norm_tensor.normal_()

tensor([[-1.5349, -0.1361,  0.4024, -0.3068],
        [-0.7589,  1.4844, -1.1028,  0.6510],
        [-1.0628,  0.0034,  0.7290,  0.5734]])

In [ ]:
#get index of all not zero elemnt
a = torch.tensor([1, 1, 1,0, 1])
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

In [ ]:
#horizontally stack four copies of a tensor
a = torch.rand(3 ,1)

print(a)

a.expand(3,4)

tensor([[0.4299],
        [0.9743],
        [0.0817]])


tensor([[0.4299, 0.4299, 0.4299, 0.4299],
        [0.9743, 0.9743, 0.9743, 0.9743],
        [0.0817, 0.0817, 0.0817, 0.0817]])

In [ ]:
#matrix-matrix mul
a = torch.rand(3, 4, 5)
b= torch.rand(3, 5,4)
torch.bmm(a, b)

tensor([[[1.0374, 1.5075, 1.3461, 1.2124],
         [0.8802, 1.4528, 1.0614, 1.0947],
         [0.8112, 1.3739, 0.8812, 0.6770],
         [1.1762, 1.5802, 1.6741, 1.5327]],

        [[2.8459, 1.5342, 2.3221, 2.1092],
         [2.6839, 1.5158, 2.1400, 1.9079],
         [1.6406, 0.5910, 1.4691, 1.4356],
         [2.1189, 0.8667, 1.6615, 1.6354]],

        [[1.3987, 0.6566, 1.4227, 0.6785],
         [1.9363, 1.3375, 1.4644, 1.5497],
         [1.0512, 0.8664, 0.6438, 0.9198],
         [1.7153, 1.2152, 1.5253, 1.3459]]])

In [ ]:
#matrix mul example 2
a = torch.rand(3 ,4 ,5)
b = torch.rand(5, 4)

torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))

tensor([[[1.2207, 0.8916, 0.8030, 0.6006],
         [1.5474, 1.1520, 1.1563, 1.6090],
         [1.1774, 0.8529, 0.8860, 1.1925],
         [0.3456, 0.3054, 0.3303, 0.4972]],

        [[1.9667, 1.3526, 1.3785, 1.6315],
         [2.1370, 1.7361, 1.6377, 1.9372],
         [1.6276, 1.0742, 0.9637, 0.8156],
         [1.4501, 1.2403, 1.1078, 1.0475]],

        [[1.1919, 0.9878, 0.9535, 1.4858],
         [1.2271, 1.0519, 1.0166, 1.2463],
         [1.2486, 1.0157, 0.9817, 1.2563],
         [1.5219, 1.2063, 1.0312, 0.9003]]])